### ISSUE TITLE
Cannot Run Colab

### ISSUE THREAD

**Issue by stavrosdidakis** [luciddreamer-cvlab/LucidDreamer#12]
Crashing to this one:

Traceback (most recent call last):   File "/content/LucidDreamer-Gaussian/app.py", line 14, in <module>     from luciddreamer import LucidDreamer   File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 34, in <module>     from gaussian_renderer import render   File "/content/LucidDreamer-Gaussian/gaussian_renderer/__init__.py", line 14, in <module>     from depth_diff_gaussian_rasterization_min import GaussianRasterizationSettings, GaussianRasterizer ModuleNotFoundError: No module named 'depth_diff_gaussian_rasterization_min'

**Comment by ironjr** [comment]
Oh... Colab version is currently not maintained by us. Please visit @camenduru: https://github.com/camenduru/LucidDreamer-Gaussian

We will be working on the official colab. In the meantime, please clone this repo and run `python app_mini.py`. It has the same functionality as the colab.

And please check if you have run the following lines in the colab code. It should be installing the module.
```
!apt install libglm-dev
!pip install /content/LucidDreamer-Gaussian/submodules/depth-diff-gaussian-rasterization-min
!pip install /content/LucidDreamer-Gaussian/submodules/simple-knn
```
