### ISSUE TITLE
error saving ply on windows

### ISSUE THREAD

**Issue by RadAlex** [luciddreamer-cvlab/LucidDreamer#18]
Hello, I have run into an issue on windows

It happens after second "aligning" iteration finishes. Seems it cannot find output folder somehow. But I can't figure out what is wrong. os. path is fine, I have printed it out just now.

Would much appreciate any information.

log as follows:

```105 / 105
Reading Training Transforms
Loading Training Cameras
Loading Preset Cameras
Number of points at initialisation :  1615299
Traceback (most recent call last):
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "c:\aigc\LucidDreamer\luciddreamer.py", line 170, in run
    gaussians = self.create(
  File "c:\aigc\LucidDreamer\luciddreamer.py", line 191, in create
    outfile = self.save_ply(os.path.join(self.save_dir, 'gsplat.ply'))
  File "C:\Users\..\anaconda3\envs\lucid\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "c:\aigc\LucidDreamer\luciddreamer.py", line 170, in run
    gaussians = self.create(
  File "c:\aigc\LucidDreamer\luciddreamer.py", line 191, in create
    outfile = self.save_ply(os.path.join(self.save_dir, 'gsplat.ply'))
  File "C:\Users\.\anaconda3\envs\lucid\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\..\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None```

**Comment by RadAlex** [comment]
got it working by changing this function, since I am not loading examples. But it is just a workaround, will brake example loading.

```    
def save_ply(self, fpath=None):
        dpath = os.path.join(self.root, self.timestamp)
        fpath = os.path.join(dpath, 'gsplat.ply')
        os.makedirs(dpath, exist_ok=True)
        self.gaussians.save_ply(fpath)
        # if fpath is None:
        # if not os.path.exists(fpath):
        #     self.gaussians.save_ply(fpath)
        # else:
        #     self.gaussians.load_ply(fpath)
        return fpath
```

**Comment by esw0116** [comment]
Hello, seems like the term ``self.save_dir`` is set to ``None``, not a specific path
Can you show us a value ``self.save_dir`` before saving a ply file?
Please add ``print(self.save_dir)`` after defining function ``create``, [L176](https://github.com/luciddreamer-cvlab/LucidDreamer/blob/265dc55629d7c8b59c9c9d9dea56ede67c71c338/luciddreamer.py#L176) to get the path of ``self.save_dir``.

**Comment by RadAlex** [comment]
it is, so I set it to outputs folder manually in init, then it worked. 

```
    def __init__(self, for_gradio=True, save_dir=None):
        self.opt = GSParams()
        self.cam = CameraParams()
        self.save_dir = "C:\\aigc\\LucidDreamer\\outputs" # save_dir
```

**Comment by esw0116** [comment]
That's a good news.
You can use argument after run.py to set save directory manually for each execution.
For example:
```bash
python run.py -s C:\\aigc\\LucidDreamer\\outputs
```

**Comment by nightdye** [comment]
> it is, so I set it to outputs folder manually in init, then it worked.
> 
> ```
>     def __init__(self, for_gradio=True, save_dir=None):
>         self.opt = GSParams()
>         self.cam = CameraParams()
>         self.save_dir = "C:\\aigc\\LucidDreamer\\outputs" # save_dir
> ```

I customized the save path according to your method, although there is a save, but there is an error in the log, saved in a non-existent path 231214_170749, maybe you still have to set the save name?
![微信图片_20231214171926](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/127379546/f1e7deb3-9df0-4de6-aff8-91d6b4c60210)
![微信图片_20231214172003](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/127379546/52d02118-c8e5-4b4b-aad5-37902b17d0a7)

**Comment by esw0116** [comment]
@nightdye,
I think this error happens when running app.py
gradio app does not use customized save_dir, instead using a folder with timestamp.
I have updated app.py to prevent that kind of error.
