### ISSUE TITLE
Error while running app.py in windows

### ISSUE THREAD

**Issue by murcje** [luciddreamer-cvlab/LucidDreamer#19]
I tried using the Gradio interface locally but I am running into an error:

`50 / 50
Reading Training Transforms
Loading Training Cameras
Loading Preset Cameras
Number of points at initialisation :  1976286
Traceback (most recent call last):
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 455, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\info\LucidDreamer\luciddreamer.py", line 191, in create
    outfile = self.save_ply(os.path.join(self.save_dir, 'gsplat.ply'))
  File "C:\Users\info\anaconda3\envs\lucid\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 455, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\info\anaconda3\envs\lucid\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\info\LucidDreamer\luciddreamer.py", line 191, in create
    outfile = self.save_ply(os.path.join(self.save_dir, 'gsplat.ply'))
  File "C:\Users\info\anaconda3\envs\lucid\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:`

When I use the commandline script run.py, it does work locally.

**Comment by esw0116** [comment]
Hello, I haven't experienced that kind of situation. There has been a similar issue before, but it occurs when executing ``run.py``.
Would you please check whether ``self.save_dir`` is set to None?
The instruction is same as [link](https://github.com/luciddreamer-cvlab/LucidDreamer/issues/18#issuecomment-1853249026).
