### ISSUE TITLE
There is an issue with the URL when executing run.py.

### ISSUE THREAD

**Issue by windsky123** [luciddreamer-cvlab/LucidDreamer#28]
python run.py
Traceback (most recent call last):
  File "/media/ma/新加卷/workspace/全景拼接毕设/LucidDreamer/run.py", line 5, in <module>
    from luciddreamer import LucidDreamer
  File "/media/ma/新加卷/workspace/全景拼接毕设/LucidDreamer/luciddreamer.py", line 36, in <module>
    import gradio as gr
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio.components.base import Component
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/components/base.py", line 21, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/blocks.py", line 28, in <module>
    from gradio import (
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/gradio/routes.py", line 116, in <module>
    client = httpx.AsyncClient()
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/httpx/_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/httpx/_client.py", line 216, in _get_proxy_map
    return {
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/httpx/_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/ma/anaconda3/envs/lucid/lib/python3.9/site-packages/httpx/_config.py", line 334, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://0.0.0.0:7891/')

**Comment by esw0116** [comment]
Hello, I think this issue is related to gradio application.
Please report the issue to [gradio](https://github.com/gradio-app/gradio) repository.
