### ISSUE TITLE
ValueError: No points given

### ISSUE THREAD

**Issue by hiroka** [luciddreamer-cvlab/LucidDreamer#3]
The error seems to occur when the jpg image size is too large.
I got an error when the image was about 600KB.
If I downsize it to 70KB or so, it works fine.

Traceback (most recent call last):
  File "/home/h/LucidDreamer/run.py", line 55, in <module>
    ld.create(rgb_cond, txt_cond, neg_txt_cond, args.campath_gen, args.seed, args.diff_steps)
  File "/home/h/LucidDreamer/luciddreamer.py", line 65, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/home/h/LucidDreamer/luciddreamer.py", line 375, in generate_pcd
    imagej = interp_grid(pixel_coord_camj.transpose(1,0), pts_colors[valid_idxj], grid, method='linear', fill_value=0).reshape(H,W,3)
  File "/home/h/miniconda3/envs/lucid/lib/python3.9/site-packages/scipy/interpolate/_ndgriddata.py", line 273, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 290, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 277, in scipy.spatial._qhull._Qhull.__init__
ValueError: No points given

**Comment by ironjr** [comment]
Ah, thanks for pointing out! We just have fixed this by adding this two line

https://github.com/luciddreamer-cvlab/LucidDreamer/blob/ed40d1e373e0daa13cfc79c02babf62d44359a86/luciddreamer.py#L517

It should be able to run smoothly now, regardless of the image size.

**Comment by AntouanK** [comment]
@ironjr I also get this error.

I'm using the colab version. 
It has
```
!git clone --recursive -b dev https://github.com/camenduru/LucidDreamer-Gaussian
```


```
100% 50/50 [00:01<00:00, 29.95it/s]
100% 50/50 [00:01<00:00, 31.65it/s]
100% 50/50 [00:01<00:00, 30.66it/s]
1 / 70
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 376, in generate_pcd
    imagej = interp_grid(pixel_coord_camj.transpose(1,0), pts_colors[valid_idxj], grid, method='linear', fill_value=0).reshape(H,W,3)
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_ndgriddata.py", line 273, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 290, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 277, in scipy.spatial._qhull._Qhull.__init__
ValueError: No points given
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 376, in generate_pcd
    imagej = interp_grid(pixel_coord_camj.transpose(1,0), pts_colors[valid_idxj], grid, method='linear', fill_value=0).reshape(H,W,3)
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_ndgriddata.py", line 273, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 290, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 277, in scipy.spatial._qhull._Qhull.__init__
ValueError: No points given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
100% 50/50 [00:01<00:00, 28.99it/s]
100% 50/50 [00:01<00:00, 34.24it/s]
100% 50/50 [00:01<00:00, 31.46it/s]
100% 50/50 [00:01<00:00, 31.45it/s]
100% 50/50 [00:01<00:00, 31.09it/s]
100% 50/50 [00:01<00:00, 30.11it/s]
100% 50/50 [00:01<00:00, 31.34it/s]
100% 50/50 [00:01<00:00, 32.23it/s]
100% 50/50 [00:01<00:00, 30.48it/s]
100% 50/50 [00:01<00:00, 30.24it/s]
100% 50/50 [00:01<00:00, 31.13it/s]
100% 50/50 [00:01<00:00, 31.43it/s]
100% 50/50 [00:01<00:00, 29.66it/s]
1 / 70
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 376, in generate_pcd
    imagej = interp_grid(pixel_coord_camj.transpose(1,0), pts_colors[valid_idxj], grid, method='linear', fill_value=0).reshape(H,W,3)
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_ndgriddata.py", line 273, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 290, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 277, in scipy.spatial._qhull._Qhull.__init__
ValueError: No points given
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 376, in generate_pcd
    imagej = interp_grid(pixel_coord_camj.transpose(1,0), pts_colors[valid_idxj], grid, method='linear', fill_value=0).reshape(H,W,3)
  File "/usr/local/lib/python3.10/dist-packages/scipy/interpolate/_ndgriddata.py", line 273, in griddata
    ip = LinearNDInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 290, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 277, in scipy.spatial._qhull._Qhull.__init__
ValueError: No points given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

**Comment by ironjr** [comment]
I just have checked the whole code. Is it fixed now?

**Comment by ironjr** [comment]
I will temporarily close this issue. If you have developed the problem again, please reopen it.

**Comment by AntouanK** [comment]
I just tried again with the colab.
The examples work.
As soon as I put my own image, I get an error.

stack trace:

```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
100% 50/50 [00:01<00:00, 25.59it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 186, in generate_pcd
    render_poses = get_pcdGenPoses(pcdgenpath)
  File "/content/LucidDreamer-Gaussian/utils/trajectory.py", line 460, in get_pcdGenPoses
    raise("Invalid pcdgenpath")
TypeError: exceptions must derive from BaseException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 61, in run
    gaussians, default_gallery = self.create(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 66, in create
    self.traindata = self.generate_pcd(rgb_cond, txt_cond, neg_txt_cond, pcdgenpath, seed, diff_steps)
  File "/content/LucidDreamer-Gaussian/luciddreamer.py", line 186, in generate_pcd
    render_poses = get_pcdGenPoses(pcdgenpath)
  File "/content/LucidDreamer-Gaussian/utils/trajectory.py", line 460, in get_pcdGenPoses
    raise("Invalid pcdgenpath")
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```
