### ISSUE TITLE
A problems encountered when starting this project locally

### ISSUE THREAD

**Issue by zhao3shi** [luciddreamer-cvlab/LucidDreamer#38]
when I execute the first command setup.py install, I get the following error, how should I solve, I have been troubled by this problem for a long time
![ce5d00afaf57b505f116570531d3e3a](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/71012898/853ff70a-a725-4e0a-a45f-2e7a57e8c4e9)

**Comment by robot0321** [comment]
Did you try to install the original rasterizer `diff-gaussian-rasterization` in [here](https://github.com/graphdeco-inria/gaussian-splatting)?
If there are no issues with the original rasterization installation but problems arise with our rasterizer, please inform me.

**Comment by thebrahman** [comment]
@robot0321 
```
LucidDreamer/submodules/depth-diff-gaussian-rasterization-min on  main via C v12.3.0-gcc via △ v3.28.3 via 🐍 v3.9.18 via 🅒 lucid 
❯ python setup.py install
running install
/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing depth_diff_gaussian_rasterization_min.egg-info/PKG-INFO
writing dependency_links to depth_diff_gaussian_rasterization_min.egg-info/dependency_links.txt
writing top-level names to depth_diff_gaussian_rasterization_min.egg-info/top_level.txt
/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'depth_diff_gaussian_rasterization_min.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'depth_diff_gaussian_rasterization_min.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying depth_diff_gaussian_rasterization_min/__init__.py -> build/lib.linux-x86_64-cpython-39/depth_diff_gaussian_rasterization_min
running build_ext
Traceback (most recent call last):
  File "/home/dev/luciddreamer/LucidDreamer/submodules/depth-diff-gaussian-rasterization-min/setup.py", line 17, in <module>
    setup(
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/install.py", line 85, in run
    self.do_egg_install()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/install.py", line 137, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 89, in run
    _build_ext.run(self)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "/home/dev/anaconda3/envs/lucid/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError: 
The detected CUDA version (12.3) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.

```
