### ISSUE TITLE
  W, H = traindata["frames"][0]["image"].size IndexError: list index out of range

### ISSUE THREAD

**Issue by Deaddawn** [luciddreamer-cvlab/LucidDreamer#64]
**Encounter error as  followed:**

Reading Training Transforms
Traceback (most recent call last):
  File "/root/szd/LucidDreamer/run.py", line 66, in <module>
    ld.create(rgb_cond, txt_cond, neg_txt_cond, args.campath_gen, args.seed, args.diff_steps, model_name=args.model_name)
  File "/root/szd/LucidDreamer/luciddreamer.py", line 188, in create
    self.scene = Scene(self.traindata, self.gaussians, self.opt)
  File "/root/szd/LucidDreamer/scene/__init__.py", line 22, in __init__
    info = readDataInfo(traindata, opt.white_background)
  File "/root/szd/LucidDreamer/scene/dataset_readers.py", line 411, in readDataInfo
    preset_minicams = loadCameraPreset(traindata, presetdata=get_camerapaths())
  File "/root/szd/LucidDreamer/scene/dataset_readers.py", line 376, in loadCameraPreset
    W, H = traindata["frames"][0]["image"].size
IndexError: list index out of range

**Comment by ZhenyuSun-Walker** [comment]
Hello, have you solved this problem? I also encounter the same difficulties!

**Comment by AntoineSchnepf** [comment]
Hello, I had the same error when using custom images. Using the image and text they suggest by default solved it (examples/Image015_animelakehouse.jpg and examples/Image015_animelakehouse.txt)
