### ISSUE TITLE
Error when running the command of run.py

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [luciddreamer-cvlab/LucidDreamer#67]
(lucid) sunzhenyu@mercury:~/Projects/LucidDreamer$ python run.py --image ~/Projects/MVDiffusion/outputs/results--20240806-140750/pano.png --text ~/Projects/MVDiffusion/outputs/results--20240803-132946/prompt.txt
Loading pipeline components...:   0%|                                                                                                         | 0/7 [00:00<?, ?it/s]An error occurred while trying to fetch runwayml/stable-diffusion-inpainting/vae: Error no file named diffusion_pytorch_model.safetensors found in directory runwayml/stable-diffusion-inpainting/vae.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...:  29%|███████████████████████████▋                                                                     | 2/7 [00:00<00:01,  4.34it/s]An error occurred while trying to fetch runwayml/stable-diffusion-inpainting/unet: Error no file named diffusion_pytorch_model.safetensors found in directory runwayml/stable-diffusion-inpainting/unet.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.36it/s]
img_size [384, 512]
Traceback (most recent call last):
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 1447, in connect
    super().connect()
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/site-packages/torch/hub.py", line 142, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sunzhenyu/Projects/LucidDreamer/run.py", line 65, in <module>
    ld = LucidDreamer(for_gradio=False, save_dir=args.save_dir)
  File "/home/sunzhenyu/Projects/LucidDreamer/luciddreamer.py", line 76, in __init__
    self.d_model = torch.hub.load('./ZoeDepth', 'ZoeD_N', source='local', pretrained=True).to('cuda')
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/site-packages/torch/hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "./ZoeDepth/hubconf.py", line 69, in ZoeD_N
    model = build_model(config)
  File "/home/sunzhenyu/Projects/LucidDreamer/./ZoeDepth/zoedepth/models/builder.py", line 51, in build_model
    return get_version(config.version_name).build_from_config(config)
  File "/home/sunzhenyu/Projects/LucidDreamer/./ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "/home/sunzhenyu/Projects/LucidDreamer/./ZoeDepth/zoedepth/models/zoedepth/zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "/home/sunzhenyu/Projects/LucidDreamer/./ZoeDepth/zoedepth/models/base_models/midas.py", line 341, in build
    midas = torch.hub.load("intel-isl/MiDaS", midas_model_type,
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/site-packages/torch/hub.py", line 555, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/home/sunzhenyu/.conda/envs/lucid/lib/python3.9/site-packages/torch/hub.py", line 199, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)

**Comment by ZhenyuSun-Walker** [comment]
Dear Sir, I'm sorry to bother you. Would you mind telling me how to fix the error shown above?
